definitions:
  http.dollarResponseList:
    type: object
info:
  contact:
    email: brendasanchez9310@gmail.com
    name: dusk
  description: cotizaciones del dolar
  title: ws-money
paths:
  /v1/dollar:
    get:
      consumes:
      - application/json
      description: get dollars by param web
      parameters:
      - description: pages to ws
        example: DOLAR_HOY
        in: query
        name: web
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/http.dollarResponseList'
        "400":
          description: ""
        "404":
          description: ""
        "500":
          description: ""
      summary: Consigue los tipos de cambio del dolar
      tags:
      - dollar
swagger: "2.0"
